target 'RCTCamera' do
  pod 'AFNetworking', '~> 2.2'
  pod 'AWSS3', '~> 2.4'
  pod 'AFOAuth2Manager', '~> 2.0'
  pod 'CocoaLumberjack', '~> 1.0'
  pod 'SSKeychain', '~> 1.2'
  pod 'FFmpegWrapper', '~> 1.0'
  pod 'PureLayout', '~> 2.0'
  pod 'Mantle', '~> 1.4'
  pod 'SDWebImage', '~> 3.6'
  pod 'FormatterKit/TimeIntervalFormatter', '~> 1.4'
end


